name: Remote-SSH Bug
description: File a bug/issue for the Remote-SSH extension
title: "[Remote-SSH Bug]: "
labels: ["ssh"]
assignees: 
   - "joshspicer"
   - "roblourens"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filling out a bug report and helping improve the Remote-SSH extension! 
        If you have a feature request for Remote-SSH please use the general `Feature request` issue creation button on the previous page.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please search [here](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aopen+is%3Aissue+label%3Assh) to see if an open or closed issue already exists for the bug you have encountered.
      options:
      - label: I have searched the existing issues
        required: true 
  - type: checkboxes
    attributes:
      label: Required Troubleshooting Steps 
      description: Please go through this troubleshooting help document and follow all the required steps, https://code.visualstudio.com/docs/remote/troubleshooting.
      options:
      - label: I have followed these troubleshooting steps
        required: true
      - label: I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)
  - type: dropdown
    attributes:
      label: Connect Locally
      description: When you tried running the ssh connection command in your local terminal what was the outcome? (please verify this connection command is exactly the same as the one in the logs labeled “Running SSH connection command”. Steps provided in troubleshoot doc.)
      options:
        - It connects successfully
        - It doesn’t connect successfully (same error message)
        - It doesn’t connect successfully (different error message)
    validations:
      required: true
  - type: textarea
    attributes:
      label: ->
      description: If your connection had a different error message when trying one of the above steps or if there was an impact by toggling the `remote.SSH.useLocalServer` setting please elaborate here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Remote-SSH Log
      description:  To find logs first click on the `View` menu at the very top of your computer screen, and then select `Output` from the dropdown. Finally, select `Remote-SSH` from the dropdown on the top right of the `Output` window. Please make sure to provide the entire log as all output is helpful to our debugging.
      value: |
        <details>
        <summary>Remote-SSH Log</summary>
        <p>

        ```
        [PASTE LOG HERE]
        ```

        </p>
        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
