name: Remote-SSH Bug
description: File a bug/issue for the Remote-SSH extension
labels: ["ssh"]
assignees: 
  - "joshspicer"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report, we appreciate your help in improving Remote - SSH!
        
        Please take the time to fill out this brief form to ensure we can triage your issue promptly.  If you have a feature request for Remote-SSH please use the general `Feature request` issue creation button on the previous page.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please search [here](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aopen+is%3Aissue+label%3Assh) to see if an open or closed issue already exists for the bug you have found.
      options:
        - label: I have searched the existing open issues and found none that apply. 
          required: true
        - label: If I find any issue of interest that is related or closed, I will included a link to it in this issue.
          required: true
  - type: checkboxes
    attributes:
      label: Required Troubleshooting Steps 
      description: Please go through the [**Troubleshooting Wiki**](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) and follow all the required steps.
      options:
        - label: I have read and performed the troubleshooting steps
          required: true
        - label: I have tried both values of the `remote.SSH.useLocalServer` setting
          required: true
        - label: My issue was **not** covered in the [**Tips and Tricks**](https://code.visualstudio.com/docs/remote/troubleshooting#_ssh-tips) linked from the [Troubleshooting Wiki](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting).
          required: true
        - label: "I will include a complete copy of my Remote - SSH logs by running **Remote-SSH: Show Log** in the command palette or from **View > Output** in the menu bar"
          required: true
  - type: dropdown
    id: copilot-chat
    attributes:
      label: "[Optional] Diagnose with Copilot"
      description: Recent versions of Remote - SSH include a [Copilot Chat Participant](https://code.visualstudio.com/docs/copilot/getting-started-chat) named `@remote-ssh`. When prompted, this participant can help diagnose issues or answer general SSH configuration questions.
      options:
        - I did not ask the @remote-ssh participant for help
        - I asked @remote-ssh but it did not help
        - I asked @remote-ssh and it helped, but I still want to report this bug
    validations:
      required: true
  - type: dropdown
    id: manually-run-ssh-cmd
    attributes:
      label: In step 2 of the troubleshooting wiki, what was the result of running the generated SSH command verbatim outside of VS Code?
      options:
        - I did not try step 2 of the troubleshooting steps
        - I COULD successfully SSH to the remote machine with the generated SSH command
        - I could NOT successfully SSH to the remote machine, and the error was the SAME to what I saw in VS Code
        - I could NOT successfully SSH to the remote machine, and the error was DIFFERENT than what I saw in VS Code
    validations:
      required: true
  - type: textarea
    attributes:
      label: Remote-SSH Log
      description: To find logs first click on the `View` menu at the very top of your computer screen, and then select `Output` from the dropdown. Finally, select `Remote-SSH` from the dropdown on the right.
      value: |
        <details>
        <summary>Remote-SSH Log</summary>
        <p>

        ```
        [PASTE LOG HERE WITHIN THE BACKTICKS TO FORMAT]
        ```
      
        </p>
        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what is actually happening
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
