name: "Classifier: Trainer"

permissions:
  id-token: write
  contents: read
  
on:
  schedule:
    - cron: 0 0 5 * *
  repository_dispatch:
    types: [trigger_classifier_trainer]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Install Additional Dependencies
        run: npm install @azure/storage-blob@12
      - name: "Run Classifier: Scraper"
        uses: ./actions/classifier/train/fetch-issues
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          areas: wsl|containers|ssh|code-server
          assignees: aeschli|roblourens|chrmarti|connor4312
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy scipy scikit-learn joblib nltk
      - name: "Run Classifier: Generator"
        run: python ./actions/classifier/train/generate-models/generate.py category
      - name: "Run Classifier: Upload"
        uses: ./actions/classifier/train/upload-models
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          blobContainerName: vscode-remote-release-models
